export const mockedData = [
    {
        id: 1,
        name: 'John Doe',
        age: 25,
        occupation: 'Software Engineer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 2,
        name: 'Jane Doe',
        age: 30,
        occupation: 'Doctor',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 3,
        name: 'Bob Smith',
        age: 35,
        occupation: 'Lawyer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 4,
        name: 'Alice Johnson',
        age: 20,
        occupation: 'Student',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 5,
        name: 'Mike Brown',
        age: 40,
        occupation: 'Teacher',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 6,
        name: 'Emily Davis',
        age: 28,
        occupation: 'Nurse',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 7,
        name: 'David Wilson',
        age: 32,
        occupation: 'Engineer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 8,
        name: 'Sarah Anderson',
        age: 27,
        occupation: 'Designer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 9,
        name: 'John Doe',
        age: 25,
        occupation: 'Software Engineer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 10,
        name: 'Jane Doe',
        age: 30,
        occupation: 'Doctor',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 11,
        name: 'Bob Smith',
        age: 35,
        occupation: 'Lawyer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 12,
        name: 'Alice Johnson',
        age: 20,
        occupation: 'Student',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 13,
        name: 'Mike Brown',
        age: 40,
        occupation: 'Teacher',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 14,
        name: 'Emily Davis',
        age: 28,
        occupation: 'Nurse',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 15,
        name: 'David Wilson',
        age: 32,
        occupation: 'Engineer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 16,
        name: 'Sarah Anderson',
        age: 27,
        occupation: 'Designer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 17,
        name: 'John Doe',
        age: 25,
        occupation: 'Software Engineer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 18,
        name: 'Jane Doe',
        age: 30,
        occupation: 'Doctor',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 19,
        name: 'Bob Smith',
        age: 35,
        occupation: 'Lawyer',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
    {
        id: 20,
        name: 'Alice Johnson',
        age: 20,
        occupation: 'Student',
        someKey: 'lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem',
    },
];
